#pragma once

#define EXCEPTION_REGS_AR(x)         ((x) * 4)
#define EXCEPTION_REGS_AR_END        256
#define EXCEPTION_REGS_SAR           256
#define EXCEPTION_REGS_LBEG          260
#define EXCEPTION_REGS_LEND          264
#define EXCEPTION_REGS_LCOUNT        268
#define EXCEPTION_REGS_PC            272
#define EXCEPTION_REGS_PS            276
#define EXCEPTION_REGS_WINDOWBASE    280
#define EXCEPTION_REGS_WINDOWSTART   284
#define EXCEPTION_REGS_WINDOWMASK    288
#define EXCEPTION_REGS_WINDOWSIZE    290
#define EXCEPTION_REGS_SIZE          292
