#pragma once

extern char __vecbase[];

typedef enum exception_cause {
    EXCEPTION_CAUSE_ILLEGAL_INSTRUCTION = 0,
    EXCEPTION_CAUSE_SYSTEM_CALL = 1,
    EXCEPTION_CAUSE_INSTRUCTION_FETCH_ERROR = 2,
    EXCEPTION_CAUSE_LOAD_STORE_ERROR = 3,
    EXCEPTION_CAUSE_LEVEL1_INTERRUPT = 4,
    EXCEPTION_CAUSE_ALLOCA = 5,
    EXCEPTION_CAUSE_INTEGER_DIVIDE_BY_ZERO = 6,
    EXCEPTION_CAUSE_SPECULATION = 7,
    EXCEPTION_CAUSE_PRIVILEGED = 8,
    EXCEPTION_CAUSE_UNALIGNED = 9,
    EXCEPTION_CAUSE_INSTR_DATA_ERROR = 12,
    EXCEPTION_CAUSE_LOAD_STORE_DATA_ERROR = 13,
    EXCEPTION_CAUSE_INSTR_ADDR_ERROR = 14,
    EXCEPTION_CAUSE_LOAD_STORE_ADDR_ERROR = 15,
    EXCEPTION_CAUSE_ITLB_MISS = 16,
    EXCEPTION_CAUSE_ITLB_MULTIHIT = 17,
    EXCEPTION_CAUSE_ITLB_PRIVILEGE = 18,
    EXCEPTION_CAUSE_ITLB_SIZE_RESTRICTION = 19,
    EXCEPTION_CAUSE_FETCH_CACHE_ATTRIBUTE = 20,
    EXCEPTION_CAUSE_DTLB_MISS = 24,
    EXCEPTION_CAUSE_DTLB_MULTIHIT = 25,
    EXCEPTION_CAUSE_DTLB_PRIVILEGE = 26,
    EXCEPTION_CAUSE_DTLB_SIZE_RESTRICTION = 27,
    EXCEPTION_CAUSE_LOAD_CACHE_ATTRIBUTE = 28,
    EXCEPTION_CAUSE_STORE_CACHE_ATTRIBUTE = 29,
    EXCEPTION_CAUSE_COPROCESSOR0_DISABLED = 32,
    EXCEPTION_CAUSE_COPROCESSOR1_DISABLED = 33,
    EXCEPTION_CAUSE_COPROCESSOR2_DISABLED = 34,
    EXCEPTION_CAUSE_COPROCESSOR3_DISABLED = 35,
    EXCEPTION_CAUSE_COPROCESSOR4_DISABLED = 36,
    EXCEPTION_CAUSE_COPROCESSOR5_DISABLED = 37,
    EXCEPTION_CAUSE_COPROCESSOR6_DISABLED = 38,
    EXCEPTION_CAUSE_COPROCESSOR7_DISABLED = 39,
    EXCEPTION_CAUSE_MAX = 64
} exception_cause_t;

//typedef struct exception_context {
//} exception_context_t;
//
//extern void* g_raw_exception_handlers[EXCEPTION_CAUSE_MAX];
